# config/meta.yml

meta_product_name: "Simple Hosting"
meta_title: "SimpleHosting - Aquileres Vacacionales "
meta_description: "Administramos propiedades vacacionales en Cartagena, Santa Marta, Barranquilla y Bucaramanga."
meta_image: "meta-image.png"                       # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
